2023-08-10 21:19:01,219 ERROR: Exception on /followers/Clem [GET] [in /Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/danielweir/highlyfe3/app/main/routes.py", line 343, in followers
    return render_template('followers.html', title='Following', user=user, followers=followers, prev_url=prev_url, next_url=next_url)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/danielweir/highlyfe3/app/templates/followers.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/danielweir/highlyfe3/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/Users/danielweir/highlyfe3/app/templates/base.html", line 63, in block 'content'
    {% block app_content %}{% endblock %}
  File "/Users/danielweir/highlyfe3/app/templates/followers.html", line 38, in block 'app_content'
    <a href="{{ url_for('main.user', username=follower_user.username) }}"style="font-size: 28px;color:white; display: block">{{ follower_user.username }}</a>
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'follower_user' is undefined
2023-08-10 21:19:22,862 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:59]
2023-08-10 21:20:00,489 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:59]
2023-08-10 21:20:23,761 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:59]
2023-08-10 21:23:11,005 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:59]
2023-08-10 21:24:08,861 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:59]
2023-08-10 21:28:09,499 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:59]
2023-08-10 21:28:35,611 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:59]
2023-08-10 22:09:57,528 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:59]
